FROM python:3.9-slim-bullseye

RUN apt-get -y update

# see https://serverfault.com/a/992421
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"

RUN apt-get install -y libopencv-dev python3-opencv git cmake g++ wget

RUN mkdir -p /app
WORKDIR /app

RUN pip install --upgrade pip

# Torch
RUN pip install torch==1.11.0 torchvision==0.12.0 --extra-index-url https://download.pytorch.org/whl/cpu
# General
RUN pip install scikit-image==0.18.* matplotlib imageio==2.31.1 opencv-python==4.8.0.74 scipy==1.10.1 pandas==2.0.3 joblib==1.3.1 einops==0.6.1 pillow==8.4.0
# Detectron2
RUN pip install "git+https://github.com/facebookresearch/detectron2.git@v0.6"
# Pytorch3D
RUN pip install fvcore==0.1.5.post20221221 
RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git@v0.7.2"
# PyTorch Geometric
RUN pip install pyg_lib==0.2.0 torch_scatter==2.0.9 torch_sparse==0.6.13 torch_cluster==1.6.0 torch_spline_conv==1.2.1 -f https://data.pyg.org/whl/torch-1.11.0+cpu.html
RUN pip install torch_geometric==2.3.1

# Copy Code
COPY . /app
# Download ckpt
RUN wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1dpYIiEqnvSd-Bd5c6bOrtBZHj8EHYh_U' -O /app/data/parcel3d.pth