_BASE_: "Base_Parcel3D.yaml"
MODEL:
  CUBE_ON: True
  MESH_ON: True
  FREEZE_BACKBONE_COMPLETE: False
  FREEZE_RPN: False
  FREEZE_BOX_HEAD: False
  FREEZE_CUBE_HEAD: False
  FREEZE_MESH_HEAD: False
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 1
  MAX_ITER: 3
MODEL:
  WEIGHTS: data/parcel3d.pth 
TEST:
  EVAL_PERIOD: 0
OUTPUT_DIR: "output/test"